services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - pnpm_store:/home/node/.pnpm-store 
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    env_file:
      - .env

volumes:
  node_modules:
  pnpm_store: 
