services:
  payload:
    build: 
      context: .
      target: runtime
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./public/media:/home/node/app/public/media
      - pnpm_store:/home/node/.pnpm-store
      - node_modules:/home/node/app/node_modules
    env_file:
      - .env

volumes:
  pnpm_store:
  node_modules: